package exotic.app.planta.model.master.configs;

public final class MasterDirectiveKeys {

    public static final String LIMITE_RECEPCIONES_PARCIALES_OCM = "LIMITE_RECEPCIONES_PARCIALES_OCM";
    public static final String DISPENSACION_NO_BLOQUEA_INICIO_PRODUCCION = "DISPENSACION_NO_BLOQUEA_INICIO_PRODUCCION";
    public static final String ENABLE_MASTER_SUPERMASTER_DIRECTIVES_ACCESS = "ENABLE_MASTER_SUPERMASTER_DIRECTIVES_ACCESS";
    public static final String MPS_SEMANAL_DIAS_BLOQUEO_EDICION = "MPS_SEMANAL_DIAS_BLOQUEO_EDICION";
    public static final String MPS_SEMANAL_PERMITIR_AGREGAR_TERMINADOS_APROBADO = "MPS_SEMANAL_PERMITIR_AGREGAR_TERMINADOS_APROBADO";
    public static final String AREA_OPERATIVA_NOISE_ENABLED = "AREA_OPERATIVA_NOISE_ENABLED";
    public static final String AREA_OPERATIVA_NOISE_INTERVAL_MINUTES = "AREA_OPERATIVA_NOISE_INTERVAL_MINUTES";
    public static final String AREA_OPERATIVA_NOISE_SAMPLE_SECONDS = "AREA_OPERATIVA_NOISE_SAMPLE_SECONDS";
    public static final String AREA_OPERATIVA_INACTIVITY_ALERT_ENABLED = "AREA_OPERATIVA_INACTIVITY_ALERT_ENABLED";
    public static final String AREA_OPERATIVA_INACTIVITY_THRESHOLD_MINUTES = "AREA_OPERATIVA_INACTIVITY_THRESHOLD_MINUTES";
    public static final String AREA_OPERATIVA_INACTIVITY_CHECK_INTERVAL_MINUTES = "AREA_OPERATIVA_INACTIVITY_CHECK_INTERVAL_MINUTES";
    public static final String AREA_OPERATIVA_PANEL_HISTORICO_TOGGLE_ENABLED = "AREA_OPERATIVA_PANEL_HISTORICO_TOGGLE_ENABLED";
    public static final int DEFAULT_LIMITE_RECEPCIONES_PARCIALES_OCM = 3;
    public static final int DEFAULT_LIMITE_RECEPCIONES_PARCIALES_OCM_PROVEEDOR = 2;
    public static final boolean DEFAULT_DISPENSACION_NO_BLOQUEA_INICIO_PRODUCCION = true;
    public static final boolean DEFAULT_ENABLE_MASTER_SUPERMASTER_DIRECTIVES_ACCESS = true;
    public static final int DEFAULT_MPS_SEMANAL_DIAS_BLOQUEO_EDICION = 2;
    public static final boolean DEFAULT_MPS_SEMANAL_PERMITIR_AGREGAR_TERMINADOS_APROBADO = false;
    public static final boolean DEFAULT_AREA_OPERATIVA_NOISE_ENABLED = false;
    public static final int DEFAULT_AREA_OPERATIVA_NOISE_INTERVAL_MINUTES = 15;
    public static final int DEFAULT_AREA_OPERATIVA_NOISE_SAMPLE_SECONDS = 2;
    public static final boolean DEFAULT_AREA_OPERATIVA_INACTIVITY_ALERT_ENABLED = true;
    public static final int DEFAULT_AREA_OPERATIVA_INACTIVITY_THRESHOLD_MINUTES = 20;
    public static final int DEFAULT_AREA_OPERATIVA_INACTIVITY_CHECK_INTERVAL_MINUTES = 10;
    public static final boolean DEFAULT_AREA_OPERATIVA_PANEL_HISTORICO_TOGGLE_ENABLED = false;

    private MasterDirectiveKeys() {
    }
}
